//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orders_Placing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt_Details
    {
        public string receiptId { get; set; }
        public string customerName { get; set; }
        public string productName { get; set; }
        public string productId { get; set; }
        public System.DateTime sellDate { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> total { get; set; }
    }
}
